server:
  port: 8081
spring:
  application:
    name: lmeng
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: hsp
  redis:
    host: 124.220.222.98
    port: 6379
    password: 123321
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.lmeng.entity # 别名扫描包
logging:
  level:
    com.lmeng: debug